const uid = (prefix) => `${prefix}_${Math.random().toString(36).slice(2, 10)}`;

export const GOOGLE_FONTS = [
  'Archivo Black',
  'Bebas Neue',
  'Manrope',
  'Montserrat',
  'Outfit',
  'Space Mono',
  'Syne',
  'Unbounded',
];

export const BLEND_MODES = [
  'source-over',
  'multiply',
  'screen',
  'overlay',
  'darken',
  'lighten',
  'difference',
];

export const CANVAS_PRESETS = [
  { id: 'square', label: 'Instagram Post', width: 1080, height: 1080 },
  { id: 'portrait', label: 'Instagram Portrait', width: 1080, height: 1350 },
];

export const BRAND_COLORS = [
  '#FFF500',
  '#9933FF',
  '#3355FF',
  '#00FDFF',
  '#00FF0A',
  '#FF6E00',
  '#FF66FF',
  '#FFFFFF',
  '#000000',
];

export const BUILT_IN_LOGOS = [
  {
    id: 'digilab-kombi-black',
    name: 'DigiLab.ai Kombi',
    src: '/logos/digilab-ai-kombi-black.png',
    defaults: {
      size: 0.28,
      x: 0.2,
      y: 0.13,
      tint: '#FFFFFF',
      preserveColor: false,
      removeWhite: true,
      whiteThreshold: 245,
    },
  },
  {
    id: 'digilab-bildmarke',
    name: 'DigiLab.ai Bildmarke',
    src: '/logos/pixel-logo.png',
    defaults: {
      size: 0.16,
      x: 0.84,
      y: 0.12,
      tint: '#FFFFFF',
      preserveColor: false,
      removeWhite: true,
      whiteThreshold: 240,
    },
  },
];

export const TEXT_ROLE_OPTIONS = [
  { value: 'headline', label: 'Headline' },
  { value: 'textbox', label: 'Textbox' },
  { value: 'body', label: 'Body' },
  { value: 'kicker', label: 'Kicker' },
  { value: 'caption', label: 'Caption' },
];

const brandColor = (index) => BRAND_COLORS[index % BRAND_COLORS.length];

export const createShapeLayer = (index, overrides = {}) => ({
  id: uid('shape'),
  kind: 'shape',
  name: overrides.name ?? `Shape ${index}`,
  visible: true,
  opacity: overrides.opacity ?? 1,
  blendMode: overrides.blendMode ?? 'source-over',
  blur: overrides.blur ?? 0,
  transform: {
    x: overrides.x ?? 0.52,
    y: overrides.y ?? 0.48,
    rotation: overrides.rotation ?? 0,
    scale: overrides.scale ?? 1,
  },
  shape: {
    fill: overrides.fill ?? '#1B1B18',
    size: overrides.size ?? 0.48,
    pixelSize: overrides.pixelSize ?? 30,
    points: overrides.points ?? 14,
    roughness: overrides.roughness ?? 0.34,
    asymmetry: overrides.asymmetry ?? 0.2,
    wobble: overrides.wobble ?? 0.16,
    squishX: overrides.squishX ?? 1,
    squishY: overrides.squishY ?? 1,
    bites: overrides.bites ?? 2,
    biteSize: overrides.biteSize ?? 0.11,
    seed: overrides.seed ?? Math.floor(Math.random() * 100000),
    imageSrc: overrides.imageSrc ?? null,
    imageName: overrides.imageName ?? 'Kein Bild',
    imageScale: overrides.imageScale ?? 1,
    imageOpacity: overrides.imageOpacity ?? 1,
    imageBlendMode: overrides.imageBlendMode ?? 'source-over',
  },
});

export const createLogoLayer = (index, overrides = {}) => ({
  id: uid('logo'),
  kind: 'logo',
  name: overrides.name ?? `Logo ${index}`,
  visible: true,
  opacity: 1,
  blendMode: 'source-over',
  blur: 0,
  assetSrc: overrides.assetSrc ?? '/logos/digilab-ai-kombi-black.png',
  assetName: overrides.assetName ?? 'DigiLab.ai Kombi',
  transform: {
    x: overrides.x ?? 0.2,
    y: overrides.y ?? 0.12,
    rotation: overrides.rotation ?? 0,
    scale: 1,
  },
  logo: {
    size: overrides.size ?? 0.27,
    tint: overrides.tint ?? '#FFFFFF',
    preserveColor: overrides.preserveColor ?? false,
    removeWhite: overrides.removeWhite ?? true,
    whiteThreshold: overrides.whiteThreshold ?? 245,
  },
});

const textDefaults = {
  headline: {
    name: 'Headline',
    x: 0.12,
    y: 0.56,
    value: 'Digitale\nEntwicklung',
    width: 0.76,
    size: 118,
    font: 'Archivo Black',
    weight: '900',
    leading: 0.92,
    tracking: -1,
    color: '#FFF500',
    align: 'left',
    uppercase: false,
    italic: false,
  },
  body: {
    name: 'Body',
    x: 0.12,
    y: 0.79,
    value: 'Kurz, klar, CI-treu. Dieses Tool erzeugt statische News-Posts mit variablen Formen und stabilen Textblöcken für Instagram.',
    width: 0.72,
    size: 34,
    font: 'Manrope',
    weight: '700',
    leading: 1.3,
    tracking: 0.1,
    color: '#F3F1E8',
    align: 'left',
    uppercase: false,
    italic: false,
  },
  textbox: {
    name: 'Textbox',
    x: 0.12,
    y: 0.74,
    value: 'Kurz, klar und gut lesbar. Diese Textbox liefert den Kontext zur Headline und bleibt ruhig genug, damit Form, Logo und CI weiter wirken koennen.',
    width: 0.58,
    size: 31,
    font: 'Manrope',
    weight: '600',
    leading: 1.24,
    tracking: 0,
    color: '#F3F1E8',
    align: 'left',
    uppercase: false,
    italic: false,
  },
  kicker: {
    name: 'Kicker',
    x: 0.12,
    y: 0.47,
    value: 'NEWS UPDATE',
    width: 0.45,
    size: 24,
    font: 'Space Mono',
    weight: '700',
    leading: 1.2,
    tracking: 2.4,
    color: '#FFFFFF',
    align: 'left',
    uppercase: true,
    italic: false,
  },
  caption: {
    name: 'Caption',
    x: 0.12,
    y: 0.93,
    value: 'digilab.ai fh dortmund',
    width: 0.28,
    size: 18,
    font: 'Space Mono',
    weight: '700',
    leading: 1.2,
    tracking: 2,
    color: '#FFFFFF',
    align: 'left',
    uppercase: true,
    italic: false,
  },
};

export const createTextLayer = (index, role = 'body', overrides = {}) => {
  const base = textDefaults[role] ?? textDefaults.body;
  return {
    id: uid('text'),
    kind: 'text',
    role,
    name: overrides.name ?? `${base.name} ${index}`,
    visible: true,
    opacity: 1,
    blendMode: 'source-over',
    blur: 0,
    transform: {
      x: overrides.x ?? base.x,
      y: overrides.y ?? base.y,
      rotation: overrides.rotation ?? 0,
      scale: 1,
    },
    text: {
      value: overrides.value ?? base.value,
      width: overrides.width ?? base.width,
      size: overrides.size ?? base.size,
      font: overrides.font ?? base.font,
      weight: overrides.weight ?? base.weight,
      leading: overrides.leading ?? base.leading,
      tracking: overrides.tracking ?? base.tracking,
      color: overrides.color ?? base.color,
      align: overrides.align ?? base.align,
      uppercase: overrides.uppercase ?? base.uppercase,
      italic: overrides.italic ?? base.italic,
    },
  };
};

export const createImageLayer = (index, overrides = {}) => ({
  id: uid('image'),
  kind: 'image',
  name: overrides.name ?? `Image ${index}`,
  visible: true,
  opacity: 1,
  blendMode: 'source-over',
  blur: 0,
  assetSrc: overrides.assetSrc ?? null,
  assetName: overrides.assetName ?? 'Kein Bild',
  transform: {
    x: overrides.x ?? 0.68,
    y: overrides.y ?? 0.34,
    rotation: overrides.rotation ?? 0,
    scale: 1,
  },
  image: {
    size: overrides.size ?? 0.34,
    fit: overrides.fit ?? 'cover',
    radius: overrides.radius ?? 0,
    tint: overrides.tint ?? '#FFFFFF',
    preserveColor: overrides.preserveColor ?? true,
    removeWhite: overrides.removeWhite ?? false,
    whiteThreshold: overrides.whiteThreshold ?? 240,
  },
});

export const createInitialScene = () => ({
  presetId: 'square',
  newsLayoutPresetId: 'news-compact',
  guides: {
    showGrid: true,
  },
  background: {
    mode: 'solid',
    colorA: '#050505',
    colorB: '#181818',
    angle: 135,
    imageSrc: null,
  },
  layers: [
    createShapeLayer(1, {
      name: 'Form Haupt',
      x: 0.56,
      y: 0.48,
      size: 0.49,
      fill: '#1B1B18',
      pixelSize: 28,
      points: 15,
      roughness: 0.36,
      asymmetry: 0.22,
      wobble: 0.15,
      squishX: 0.98,
      squishY: 1.18,
      bites: 2,
      biteSize: 0.12,
    }),
    createShapeLayer(2, {
      name: 'Form Akzent',
      x: 0.14,
      y: 0.48,
      size: 0.15,
      fill: brandColor(0),
      pixelSize: 18,
      points: 10,
      roughness: 0.32,
      asymmetry: 0.18,
      wobble: 0.11,
      squishX: 1.1,
      squishY: 0.94,
      bites: 1,
      biteSize: 0.08,
    }),
    createLogoLayer(1),
    createTextLayer(1, 'kicker'),
    createTextLayer(1, 'headline'),
    createTextLayer(1, 'textbox'),
    createTextLayer(1, 'caption'),
  ],
});
